language:  java
env:
  -DB=mysql
jdk: openjdk11
services:
  - mysql
before_install:
  - mysql -e 'GRANT CREATE USER ON *.* TO \'root\'@\'%\' IDENTIFIED BY \'12345\'; FLUSH PRIVILEGES; CREATE DATABASE IF NOT EXISTS gupb;'
branches:
  only:
    - main
    - /feature\/.+/
